### ISSUE TITLE
The DirectoryNameDraggableEntry class should make use of a childElements() method

### ISSUE THREAD

**Issue by djalbat** [djalbat/Easy-DragAndDrop#31]
And possibly others.

**Comment by jecs-imperial** [comment]
Specifically, the `Entries` and `ToggleButton` elements can be child elements, and expose the requisite methods through `parentContext()` methods.

**Comment by djalbat** [comment]
This has been done for the `DraggableEntry` class. It's the `DirectoryNameDraggbleEntry` class with this issue.

**Comment by djalbat** [comment]
Done.
